### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Bunder99** [salman-bhai/WhatsApp-Web#12]
Hi! I met a lot of problems when installing and running your WhatsApp-Web... I have Kali Linux (4.13.0-kali1-amd64). Requirements are installed successfully, but:

1. Command "source activate wa-web" doesn't work and I don't understand what it does (I get bash error)

2. After running "python wa.py" I get:

Traceback (most recent call last):
  File "wa.py", line 10, in <module>
    d = webdriver.Chrome('/root/WhatsApp-Web/chromedriver')  # Optional argument, if not specified will search path.
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.13.0-kali1-amd64 x86_64)

What should I do? Could you help me? Thanks in advance!

**Comment by masterwaqar** [comment]
pip install chromedriver

then add chromedriver Path at wa.py

replace 
webdriver.Chrome('/home/salman/All-Projects/WhatsApp-Web/chromedriver')

with 

webdriver.Chrome('/bin/chromedriver')

**Comment by Bunder99** [comment]
Done, but I've got the same errors...

**Comment by sbshah97** [comment]
```
Hi! I met a lot of problems when installing and running your WhatsApp-Web... I have Kali Linux (4.13.0-kali1-amd64). Requirements are installed successfully, but:

    Command "source activate wa-web" doesn't work and I don't understand what it does (I get bash error)
```
That is for activating a Python Virtual Environment. Do you have Python Virtual Environment installed in your system?

**Comment by sbshah97** [comment]
@Bunder99 what is the path that you have given for Chromedriver

**Comment by Bunder99** [comment]
Python Virtual Environment is installed and activated before start WhatsApp-Web. But I can't activate it by your way "source activate wa-web", because there is no way to activate the folder, is it? 
chromedriver=2.33.506092, path - /usr/local/bin/chromedriver, changed in wa.py. The errors are the same.
I tried to install Chrome browser, but I have no profit. What should I do further? Thank for your help.
